name: My First Workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4 

        - name: List and Read files 
          run: |
            echo "Welcome to my first Github Actions Workflow!"
            ls -ltra
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "I have a DRAGON.... DRACARYS" >> dragon.txt