name: Generate ASCII Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4 

        - name: List files
          run: ls -ltra

        - name: Execute Cowsay Script
          run: |
            chmod +x .github/workflows/ascii-script.sh
            ./.github/workflows/ascii-script.sh