name: Matrix Configuration
on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, windows-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      images: alpine
        runs-on: ${{matrix.os}}
        steps:
        - name: Docker Details
          run: docker info

        - name: Run Image on ${{matrix.os}}
          run: docker run ${{matrix.images}}